display_name: "qwen3.8-flash-next-nvfp4"
api_name:
  openai: "Qwen3.8-Flash-Next-NVFP4"
default_provider: openai
api_kwargs:
  openai:
    top_p: 0.95
    extra_body:
      top_k: 20
      chat_template_kwargs:
        reasoning_effort: xhigh
